### ISSUE TITLE
Observations from peer-to-peer code review

### ISSUE THREAD

**Issue by lucilapastore** [kitpao/capstone_project#2]
- [x] you could change the div tags for semantic tags, like section and aside or something like that.
Reference:
Semantic tags https://www.w3schools.com/html/html5_semantic_elements.asp

- [x] in the body and footer you have inline-style. remember to replace them.

- [x] the image is blured. you could find a better image in unsplash or https://www.producthunt.com/

- [x] add some image or video to the readme of git hub.

**Comment by kitpao** [comment]
Done :)
